# Generated by Django 3.2.13 on 2022-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_headerservices_itaboutmodels_mainpageaboutmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItAboutModels',
        ),
    ]
